export interface Villager {
    id: number,
    birthday: string,
    catchPhrase: string,
    clothing: string,
    gender: string,
    hobby: string,
    iconURI: string,
    imageURI: string,
    name: string,
    personality: string,
    saying: string,
    species: string,
    sign: string,
    favColors: string[],
    favStyles: string[],
    houseExterior: string,
    houseInterior: string,
    houseMusic: string,
    photoURL: string
}